core_core:
    resource: "@CoreCoreBundle/Controller/"
    type:     annotation
    prefix:   /

os_communications:
    resource: "@OSCommunicationsBundle/Controller/"
    type:     annotation
    prefix:   /comm

os_game:
    resource: "@OSGameBundle/Controller/"
    type:     annotation
    prefix:   /

os_user:
    resource: "@OSUserBundle/Controller/"
    type:     annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"