# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]

services:
    os_user.registration.form.type:
        class: OS\UserBundle\Form\RegistrationFormType
        tags:
            - { name: form.type, alias: os_user_registration }

    chat:
        class: OS\CommunicationsBundle\Service\Chat
        arguments:
            - @doctrine.orm.default_entity_manager