<?php

namespace OS\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharsRepository extends EntityRepository
{
}
