<?php

namespace OS\GameBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MonsterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MonsterRepository extends EntityRepository
{
    /**
     * @param Map $map
     * @return array
     */
    public function findByMap(Map $map) {
        $qb = $this->createQueryBuilder('m')
            ->join('m.position', 'p')
            ->where('p.map = :param')
            ->setParameter('param', $map)
            ->getQuery();

        return $qb->getResult();
    }
}
