<?php

namespace Proxies\__CG__\OS\GameBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Map extends \OS\GameBundle\Entity\Map implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'id', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'code', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'json', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'bgMusic', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'positions', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'fullJson'];
        }

        return ['__isInitialized__', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'id', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'code', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'json', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'bgMusic', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'positions', '' . "\0" . 'OS\\GameBundle\\Entity\\Map' . "\0" . 'fullJson'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Map $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setJson($json)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setJson', [$json]);

        return parent::setJson($json);
    }

    /**
     * {@inheritDoc}
     */
    public function getJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getJson', []);

        return parent::getJson();
    }

    /**
     * {@inheritDoc}
     */
    public function addPosition(\OS\GameBundle\Entity\Position $positions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPosition', [$positions]);

        return parent::addPosition($positions);
    }

    /**
     * {@inheritDoc}
     */
    public function removePosition(\OS\GameBundle\Entity\Position $positions)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePosition', [$positions]);

        return parent::removePosition($positions);
    }

    /**
     * {@inheritDoc}
     */
    public function getPositions()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPositions', []);

        return parent::getPositions();
    }

    /**
     * {@inheritDoc}
     */
    public function setCode($code)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCode', [$code]);

        return parent::setCode($code);
    }

    /**
     * {@inheritDoc}
     */
    public function getCode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCode', []);

        return parent::getCode();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function toJSON()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toJSON', []);

        return parent::toJSON();
    }

    /**
     * {@inheritDoc}
     */
    public function setBgMusic($bgMusic)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBgMusic', [$bgMusic]);

        return parent::setBgMusic($bgMusic);
    }

    /**
     * {@inheritDoc}
     */
    public function getBgMusic()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBgMusic', []);

        return parent::getBgMusic();
    }

    /**
     * {@inheritDoc}
     */
    public function setFullJson($fullJson)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFullJson', [$fullJson]);

        return parent::setFullJson($fullJson);
    }

    /**
     * {@inheritDoc}
     */
    public function getFullJson()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFullJson', []);

        return parent::getFullJson();
    }

}
